"""Application configuration for PrintSentinel."""

import os
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent

MODEL_PATH = BASE_DIR / "models" / "model.pt"
SAMPLE_VIDEO_PATH = BASE_DIR / "assets" / "demo.mp4"
CAPTURES_DIR = BASE_DIR / "captures"
LOGS_DIR = BASE_DIR / "logs"
EVENTS_CSV_PATH = LOGS_DIR / "events.csv"

FAILURE_CLASSES = ("spaghetti", "stringing", "zits")
CONFIDENCE_THRESHOLD = 0.35
CONSECUTIVE_FAIL_FRAMES = 3
ALERT_COOLDOWN_SECONDS = 20
ALERT_BEEP_ENABLED = False

PRINTER_BACKEND = os.getenv(
    "PRINTSENTINEL_PRINTER_BACKEND",
    os.getenv("PRINTER_BACKEND", "simulated"),
).strip()
PRINTER_ACTION = os.getenv(
    "PRINTSENTINEL_PRINTER_ACTION",
    os.getenv("PRINTER_ACTION", "stop"),
).strip()
PRINTER_BASE_URL = os.getenv(
    "PRINTSENTINEL_PRINTER_BASE_URL",
    os.getenv("PRINTER_BASE_URL", ""),
).strip()
PRINTER_STOP_ENDPOINT = os.getenv(
    "PRINTSENTINEL_PRINTER_STOP_ENDPOINT",
    os.getenv("PRINTER_STOP_ENDPOINT", "/stop"),
).strip()
PRINTER_PAUSE_ENDPOINT = os.getenv(
    "PRINTSENTINEL_PRINTER_PAUSE_ENDPOINT",
    os.getenv("PRINTER_PAUSE_ENDPOINT", "/pause"),
).strip()
PRINTER_HEALTH_ENDPOINT = os.getenv(
    "PRINTSENTINEL_PRINTER_HEALTH_ENDPOINT",
    os.getenv("PRINTER_HEALTH_ENDPOINT", "/health"),
).strip()
PRINTER_REQUEST_TIMEOUT_SECONDS = float(
    os.getenv(
        "PRINTSENTINEL_PRINTER_REQUEST_TIMEOUT_SECONDS",
        os.getenv("PRINTER_REQUEST_TIMEOUT_SECONDS", "3"),
    )
)

SIMULATED_ACTION = PRINTER_ACTION

WINDOW_NAME = "PrintSentinel"
STATUS_MONITORING = "STATUS: MONITORING"
STATUS_FAIL_DETECTED = "STATUS: FAIL DETECTED -> STOP PRINTER"
STATUS_CONFIRMING = "STATUS: CHECKING"

OVERLAY_HEIGHT = 128
OVERLAY_PADDING = 16
OVERLAY_LINE_HEIGHT = 23
OVERLAY_FONT_SCALE = 0.55
OVERLAY_TITLE_FONT_SCALE = 0.75
OVERLAY_THICKNESS = 1
OVERLAY_TITLE_THICKNESS = 2

COLOR_STATUS_OK = (0, 150, 0)
COLOR_STATUS_FAIL = (0, 0, 220)
COLOR_STATUS_CHECKING = (0, 140, 220)
COLOR_OVERLAY_BACKGROUND = (28, 28, 28)
COLOR_STATUS_TEXT = (255, 255, 255)
COLOR_STATUS_DETAIL = (235, 235, 235)
